# Generated by Django 3.2.5 on 2021-07-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='inviter',
            field=models.CharField(max_length=20),
        ),
    ]
