# Generated by Django 3.2.5 on 2021-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_membership_inviter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-sign_up_time'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='password', max_length=256),
        ),
        migrations.AddField(
            model_name='member',
            name='sign_up_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
