# Generated by Django 3.2.5 on 2021-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_member_sign_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='student_id',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
