# Generated by Django 3.2.5 on 2021-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_member_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='real_name',
            field=models.CharField(default='real_name', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='username', max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
